networks:
  default:
    name: rapptor

volumes:
  rapptor-user-data:
    name: rapptor-user-data
  rapptor-tls-certs:
    name: rapptor-tls-certs

services:
  rapptoros:
    container_name: service.93million.rapptor
    image: ${RAPPTOR_CUSTOM_IMAGE_URI:-ghcr.io/93million/rapptor:0.1.2}
    restart: always
    environment:
      NODE_ENV: production
      RAPPTOR_APP_STORE_REPO: ${RAPPTOR_CUSTOM_APP_STORE_REPO:-https://github.com/93million/rapptor-app-store/}
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 4000:4000
      - 4002:4002
    volumes:
      - ./:/app/system:rw
      - ./.env:/app/.env:rw
      - ./apps:/app/apps:rw
      - ./appstore:/app/appstore:rw
      - ./appstorerepo:/appstorerepo:ro
      - ./accounts:/app/accounts:rw
      - ./base:/base:rw
      - rapptor-tls-certs:/etc/certcache:ro
      - ./docker/config.json:/app/docker/config.json:ro
      - ./var/token:/app/var/token:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - rapptor-user-data:/files:rw
    labels:
      com.93million.containerType: system
  certcache:
    container_name: certcache
    image: ghcr.io/93million/certcache:1.0.0
    restart: always
    volumes:
      - ./certcache/cache/:/certcache/cache/:rw
      - ./certcache/catkeys/:/certcache/catkeys/:rw
      - ./certcache/conf/:/certcache/conf/:ro
      - rapptor-tls-certs:/certcache/certs/:rw
    env_file:
      - .env
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    labels:
      com.93million.containerType: system
  docker-container:
    image: docker:26.1.0-dind-alpine3.19
    container_name: dockerrun
    restart: 'no'
    labels:
      com.93million.containerType: system
    command: ['true']
