networks:
  default:
    name: rapptor

volumes:
  rapptor-data:
    name: rapptor-data

services:
  rapptorcontrolpanel:
    container_name: service.93million.rapptor
    image: gitlab.93m.org:5050/93m/rapptor/system/os:dev
    restart: always
    environment:
      NODE_ENV: development
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
      RAPPTOR_APP_STORE_REPO: 'https://gitlab.93m.org/93m/rapptor/app-store/app.93million.appstore.git'
      RAPPTOR_DOCKER_CONFIG_PATH: '/app/docker/config.json'
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 9229:9229
      - 9231:9231
      - 4000:4000
      - 4002:4002
    volumes:
      - ./:/app/system:rw
      - ./.env:/app/.env:rw
      - ./apps:/app/apps:rw
      - ./appstore:/app/appstore:rw
      - ./appstorerepo:/appstorerepo:ro
      - ./accounts:/app/accounts:rw
      - ./base:/base:rw
      - ./control-panel/entrypoint.sh:/app/entrypoint.sh:rw
      - ./control-panel/nodemon.json:/app/nodemon.json:ro
      - ./control-panel/package.json:/app/package.json:ro
      - ./control-panel/package-lock.json:/app/package-lock.json:rw
      - ./control-panel/src/:/app/src/:ro
      - ./control-panel/var/templates:/app/var/templates:ro
      - ./control-panel/web/dist/:/app/web/dist/:ro
      - ./control-panel/web/index.html:/app/web/index.html:ro
      - ./control-panel/web/package.json:/app/web/package.json:ro
      - ./control-panel/web/package-lock.json:/app/web/package-lock.json:rw
      - ./control-panel/web/src/:/app/web/src/:ro
      - ./control-panel/web/vite.config.ts:/app/web/vite.config.ts:ro
      - ./control-panel/tsconfig.json:/app/tsconfig.json:ro
      - ./dev/ssl/devcert:/etc/certcache/web:ro
      - ./docker/config.json:/app/docker/config.json:ro
      - ./var/setup:/app/var/setup:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - rapptor-data:/files:rw
    labels:
      com.93million.containerType: system
  docker-container:
    image: docker:26.1.0-dind-alpine3.19
    container_name: dockerrun
    restart: 'no'
    labels:
      com.93million.containerType: system
    command: ['true']
