[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn
[ dn ]
C = UK
ST = Tyne and Wear
L = Newcastle upon Tyne
O = 93 Million Ltd
OU = 93 Million Ltd
CN = punk.loc
[ req_ext ]
subjectAltName = @alt_names
[ alt_names ]
DNS.1 = *.punk.loc
